### ISSUE TITLE
Not tagged as compatible with 1.19.x

### ISSUE THREAD

**Issue by James103** [Parzivail-Modding-Team/HereBeNoDragons#3]
The mod is not tagged as compatible with 1.19.x on Modrinth, which causes some launchers, including Prism Launcher to not be able to download the mod at all and others to throw an error while trying to update the mod.

The mod does actually appear to work on 1.19.2 on my testing, and is likely to work on other 1.19.x versions.

**Comment by parzivail** [comment]
Should be fixed now, thanks
